"""Domain events for the Messaging bounded context."""

from __future__ import annotations

from dataclasses import dataclass

from searce_scout.shared_kernel.domain_event import DomainEvent


@dataclass(frozen=True)
class MessageGeneratedEvent(DomainEvent):
    """Raised when a new message is generated by the AI engine."""

    channel: str = ""
    tone: str = ""
    quality_score: float = 0.0


@dataclass(frozen=True)
class MessageApprovedEvent(DomainEvent):
    """Raised when a message is approved for sending."""


@dataclass(frozen=True)
class ToneAdjustedEvent(DomainEvent):
    """Raised when a message's tone is changed."""

    old_tone: str = ""
    new_tone: str = ""
